---
# These instructions assumes that the variable "all_vms" is already declared.

- name: Declare domain variable for domain.yml
  set_fact:
    domain: "{{ item.value }}"

- name: Declare domain.name variable for domain.yml
  set_fact:
    domain: "{{ domain | combine( { 'name': item.key } ) }}"

- include_tasks: do_delete_domain.yml
  when: domain.name in all_vms.list_vms

- name: Stat of the directory of the domain
  stat:
    path: "{{ group_vars.cloud_image.local_saved_dir }}/{{ domain.name }}/"
  register: result

- name: Cleanup the directory of the domain
  file:
    state: absent
    path: "{{ group_vars.cloud_image.local_saved_dir }}/{{ domain.name }}/"
  when: result.stat.exists

