---
- name: Stat a directory /opt/vxlan-builder/ exists
  stat:
    path: "/opt/vxlan-builder/"
  register: main_directory

- name: Stat a file /opt/vxlan-builder/set_vxlan_env.sh exists
  stat:
    path: "/opt/vxlan-builder/set_vxlan_env.sh"
  register: main_file

- name: Include do_prepare_vxlan_builder.yml if vxlan-builder has not been prepared.
  include: do_prepare_vxlan_builder.yml
  when: not main_directory.stat.exists

- name: B
  block:
    - name: A-1
      include: do_prepare_vxlan_builder.yml
      when: not main_file.stat.exists

    # This task need not do any tasks to prepare vxlan-builder if it has already been prepared.
    #   -> (main_file.stat.exists == true) and (main_directory.stat.exist == true)
  when: main_directory.stat.exists

