---
# List defined domains
- name: Get defined domains
  community.libvirt.virt:
    command: list_vms
  register: defined_domains

# List running domains
- name: Get running domains
  community.libvirt.virt:
    command: list_vms
    state: running
  register: running_domains

- include: create_and_run_domain.yml
  when: "instance.name not in defined_domains.list_vms"

# Start domain if the domain was already defined but not running.
# Domain was already existed and running if create_and_run_domain.yml was executed previously.
- name: Domain should be running
  community.libvirt.virt:
    name: "{{ instance.name }}"
    state: running
  when: "instance.name not in running_domains.list_vms"

#- name: Add additional interfaces to the domain
#  ansible.builtin.command:
#    argv: ["virsh", "attach-interface", "--domain", "{{ instance.name }}", "--type", "network", "--model", "virtio", "--config", "--live"]

#virsh attach-interface --domain vm1 --type network \
#        --source openstackvms --model virtio \
#        --mac 52:54:00:4b:73:5f --config --live

