---
# List defined domains
- name: Get defined domains
  community.libvirt.virt:
    command: list_vms
  register: defined_domains

# List running domains
- name: Get running domains
  community.libvirt.virt:
    command: list_vms
    state: running
  register: running_domains

# Create domain and run it if the domain was not defined
- include: create_and_run_domain.yml
  when: "{{ instance.name }} in {{ defined_domains }}"

# Start domain if the domain was already defined but not running.
# Domain was already existed and running if create_and_run_domain.yml was executed previously.
- include: run_domain.yml
  when: "{{ instance.name }} not in {{ running_domains }}"

