---
- name: Define base image name
  set_fact:
    base_image_name: "{{ group_vars.cloud_image.get_url | basename }}"

- name: Register cloud image stat
  stat:
    path: "{{ group_vars.cloud_image.local_saved_dir }}/{{ base_image_name }}"
  register: cloud_image

- name: Download cloud image of ubuntu if it was not existed
  get_url:
    url: "{{ group_vars.cloud_image.get_url }}"
    dest: "{{ group_vars.cloud_image.local_saved_dir }}/{{ base_image_name }}"
  when: not cloud_image.stat.exists

# do_domain will read item.key and item.value.
# This instruction assumes that they are already declared by calling by "with_dict".
#
# If ex_instance is declared:
#   -> Include domain.yml only if current instance that will be created is same with ex_instance.
# If ex_instance is not declared:
#   -> Include domain.yml for all instances.
- name: Include create_domain.yml
  include: create_domain.yml
  when: "(ex_instance is not defined) or ((ex_instance is defined) and (ex_instance == item.key))"
  with_dict: "{{ group_vars.kvm.instances }}"

