---
- name: Define base image name
  set_fact:
    base_image_name: "{{ group_vars.cloud_image.get_url | basename }}"

- name: Register cloud image stat
  stat:
    path: "{{ group_vars.cloud_image.local_saved_dir }}/{{ base_image_name }}"
  register: cloud_image

- name: Download cloud image of ubuntu if it was not existed
  get_url:
    url: "{{ group_vars.cloud_image.get_url }}"
    dest: "{{ group_vars.cloud_image.local_saved_dir }}/{{ base_image_name }}"
  when: not cloud_image.stat.exists

- include_tasks: domain.yml
  with_dict: "{{ group_vars.kvm.instances }}"

