---

- name: Define base image name
  set_fact:
    base_image_name: "{{ group_vars.cloud_image.get_url | basename }}"

- name: Register cloud image stat
  stat:
    path: "{{ group_vars.cloud_image.local_saved_dir }}/{{ base_image_name }}"
  register: cloud_image

#- name: Debug
#  ansible.builtin.debug:
#    msg: "{{ base_image_name }}"

- name: Download cloud image of ubuntu if it was not existed
  get_url:
    url: "{{ group_vars.cloud_image.get_url }}"
    dest: "{{ group_vars.cloud_image.local_saved_dir }}/{{ base_image_name }}"
  when: not cloud_image.stat.exists

- name: Create external snapshots
  ansible.builtin.command:
    argv: ["qemu-img", "create", "-f", "qcow2", "-b", "{{ base_image_name }}", "{{ item.name }}.img"]
  args:
    chdir: "{{ group_vars.cloud_image.local_saved_dir }}"
  loop: "{{ group_vars.kvm.instances }}"

- name: Create external snapshots
  ansible.builtin.debug:
    msg: "{{ item.name }}"
  loop: "{{ group_vars.kvm.instances }}"

#- name: Debug instances
#  ansible.builtin.debug:
#    msg: "name={{ item.name }}, memory={{ item.memory }}"
#  loop: "{{ group_vars.kvm.instances }}"



