---
###- name: Include download_base_image/main.yml
###  include_tasks: download_base_image/main.yml

# do_domain will read item.key and item.value.
# This instruction assumes that they are already declared by calling by "with_dict".
#
# If ex_instance is declared:
#   -> Include domain.yml only if current instance that will be created is same with ex_instance.
# If ex_instance is not declared:
#   -> Include domain.yml for all instances.
- name: "Include create_domain/main.yml. (Debug ex_instance is \"{{ ex_instance }}\")"
  include_tasks: create_domain/main.yml
  when: "(ex_instance is not defined) or ((ex_instance is defined) and (ex_instance == item.key))"
  with_dict: "{{ group_vars.kvm.instances }}"

