---
# cloud_image: An element of cloud-image that has id, get_url, type, os_variant etc
- name: "Define base image name {{ cloud_image.get_url | basename }}"
  set_fact:
    base_image_name: "{{ cloud_image.get_url | basename }}"

- name: "Register cloud image stat {{ group_vars.kvm.local_saved_dir }}/{{ base_image_name }}"
  stat:
    path: "{{ group_vars.kvm.local_saved_dir }}/{{ base_image_name }}"
  register: cloud_image_path

- name: "A directory that will be downloaded a cloud-image should be existed ({{ group_vars.kvm.local_saved_dir }})"
  ansible.builtin.file:
    path: "{{ group_vars.kvm.local_saved_dir }}"
    state: directory
    recurse: yes
    mode: '0755'

- name: "Download cloud image of ubuntu if it was not existed"
  get_url:
    url: "{{ cloud_image.get_url }}"
    dest: "{{ group_vars.kvm.local_saved_dir }}/{{ base_image_name }}"
  when: not cloud_image_path.stat.exists
