---
- name: Print the gateway for each host when defined
  ansible.builtin.debug:
    msg: "fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"

#- name: Flush any rules in FORWARD
#  ansible.builtin.iptables:
#    chain: FORWARD
#    flush: yes
#
#- name: Accept all to FORWARD
#  ansible.builtin.iptables:
#    chain: FORWARD
#    jump: ACCEPT

