---
- name: Flush any rules in FORWARD
  ansible.builtin.iptables:
    chain: FORWARD
    flush: yes

- name: Accept all to FORWARD
  ansible.builtin.iptables:
    chain: FORWARD
    jump: ACCEPT

- name: Debug
  ansible.builtin.debug:
    msg:
      - "======================================================================================================================="
      - "[WARNING]"
      - "Iptables chain FORWARD are all set ACCEPTED to be able to forward any packet during KVM instances and any outside networks"
      - "even if filters which is for Docker has been set."
      - "======================================================================================================================="

