---
# Arch Linux requires cloud-localds for the command 
# cloud-localds

- include_tasks: arch_linux_tasks.yml
  when: ansible_distribution == 'Archlinux'

- name: Find a command cloud-localds
  shell: command -v cloud-localds > /dev/null 2>&1
  register: is_cloud_localds_existed

- name: Is cloud-localds command was existed
  fail: msg="cloud-localds command was not existed"
  when: is_cloud_localds_existed.rc != 0

- name: libvirtd should be enabled
  ansible.builtin.service:
    name: libvirtd
    enabled: yes

- name: libvirtd should be running
  ansible.builtin.service:
    name: libvirtd
    state: started

