---
# Arch Linux requires cloud-localds for the command 
# cloud-localds

- include_tasks: arch_linux_tasks.yml
  when: ansible_distribution == 'Archlinux'

- name: libvirtd should be enabled
  ansible.builtin.service:
    name: libvirtd
    enabled: yes

- name: libvirtd should be running
  ansible.builtin.service:
    name: libvirtd
    state: started

