---
- name: "Declare a variable num_of_additional_disks"
  set_fact:
    num_of_additional_disks: "{{ instance.additional_disks | length | int }}"

- name: "Validate additional disk for cinder node. [instance.name={{ instance.name }}]"
  ansible.builtin.fail:
    msg: "This script only support 1 additional disks for node of cinder. Num of disks you specified is {{ num_of_additional_disks }}"
  when: "(instance.name | regex_search(\"^.*cinder[0-9]+.*$\")) and (num_of_additional_disks != \"1\")"

- name: "Validate additional disk for other than cinder node. [instance.name={{ instance.name }}]"
  ansible.builtin.fail:
    msg: "This script support from 1 to 7 additional disks for node other than cinder. Num of disks you specified is {{ num_of_additional_disks }}"
  when: "(not (instance.name | regex_search(\"^.*cinder[0-9]+.*$\"))) and (num_of_additional_disks | int > 7)"

